shared: &shared
  github:
    base_url: <%= ENV.fetch('GITHUB_BASE_URL' , 'https://api.github.com')%>
    search_repositories_path: <%= ENV.fetch('GITHUB_SEARCH_REPOSITORIES_PATH', '/search/repositories')%>
    authorization_toke: <%= ENV.fetch('GITHUB_AUTHORIZTION_TOKEN', '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')%> # this token is used to authorize requests to github, which enable us to send more requests to github, the only permission this token has is the access public repositories
    username: <%= ENV.fetch('GITHUB_USERNAME', 'kamal-buqaileh')%>

development:
  <<: *shared
test:
  <<: *shared
production:
  <<: *shared
